/**
 * The Claude Code worker adapter.
 *
 * Built against the CLI actually installed on this machine — `claude` 2.1.234 —
 * inspected with `claude --help`, not from memory:
 *
 *   -p, --print                 non-interactive; print and exit
 *   --output-format json        one result object on stdout
 *   --model <model>             full name, e.g. claude-opus-5
 *   --session-id <uuid>         choose the session id up front
 *   -r, --resume [sessionId]    continue a prior session
 *   --permission-mode <mode>    acceptEdits | bypassPermissions | plan | …
 *   --add-dir <dirs...>         extra directories the tools may reach
 *   --max-budget-usd <amount>   hard spend ceiling (print mode only)
 *   --append-system-prompt      added to the default system prompt
 *
 * Three choices worth stating:
 *
 * 1. The prompt goes in on STDIN, not as an argv positional. Worker prompts
 *    carry a diff and several files; argv has a length limit and shows up in
 *    `ps`. stdin has neither problem.
 *
 * 2. `--session-id` is generated by the controller BEFORE the run. If stdout
 *    is unparseable — the worker was killed, the format changed — the run
 *    record still names a resumable session. Learning the id only from a
 *    successful response is learning it exactly when it is least needed.
 *
 * 3. Resume is used when available and is never depended upon (B3).
 *    `supportsResume()` reads `--help`; when the flag is absent the repair turn
 *    is a fresh invocation carrying the original task, the previous summary,
 *    the findings and the diff. Same information, more tokens — a degradation,
 *    not a failure.
 */

import { spawn, execFile } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { promisify } from 'node:util';
import { CODES, fail } from './errors.mjs';
import { redact } from './redaction.mjs';

const execFileAsync = promisify(execFile);

export const DEFAULT_WORKER_MODEL = 'claude-opus-5';

/**
 * Permission mode for the worker.
 *
 * `acceptEdits` lets it write files in its own worktree without a prompt, which
 * is the whole point of an unattended run, while still stopping short of
 * `bypassPermissions`. The containment that matters is elsewhere and is
 * structural: a dedicated worktree, a boundary check on the resulting diff, and
 * gates the controller runs itself.
 */
export const DEFAULT_PERMISSION_MODE = 'acceptEdits';

export async function claudeAvailable({ bin = 'claude', execImpl = execFileAsync } = {}) {
  try {
    const { stdout } = await execImpl(bin, ['--version'], { timeout: 20_000 });
    return { ok: true, version: stdout.trim().split('\n')[0] ?? '' };
  } catch (error) {
    return { ok: false, version: null, error: redact(error?.message ?? String(error)) };
  }
}

/** Ask the installed binary, rather than assuming a flag this repo remembers. */
export async function supportsResume({ bin = 'claude', execImpl = execFileAsync } = {}) {
  try {
    const { stdout } = await execImpl(bin, ['--help'], { timeout: 20_000 });
    return /--resume/.test(stdout);
  } catch {
    return false;
  }
}

/**
 * Build the argv for one worker turn. Pure, so the tests can assert the exact
 * invocation without running anything.
 */
export function buildArgs({
  model = DEFAULT_WORKER_MODEL,
  sessionId,
  resumeSessionId = null,
  permissionMode = DEFAULT_PERMISSION_MODE,
  maxBudgetUsd = null,
  addDir = null,
  effort = null,
} = {}) {
  const args = ['-p', '--output-format', 'json', '--model', model, '--permission-mode', permissionMode];

  if (resumeSessionId) {
    args.push('--resume', resumeSessionId);
  } else if (sessionId) {
    args.push('--session-id', sessionId);
  }
  if (maxBudgetUsd !== null && maxBudgetUsd !== undefined) {
    args.push('--max-budget-usd', String(maxBudgetUsd));
  }
  if (addDir) args.push('--add-dir', addDir);
  if (effort) args.push('--effort', effort);

  return args;
}

/**
 * Parse `--output-format json`.
 *
 * Defensive on purpose: the controller needs `session_id` and the final text,
 * and must not break when the payload gains fields. An unparseable payload is a
 * failed turn — never "it probably worked".
 */
export function parseResult(stdout) {
  let payload;
  try {
    payload = JSON.parse(stdout);
  } catch {
    fail(CODES.WORKER_MALFORMED, `worker output was not JSON: ${redact(stdout).slice(0, 400)}`);
  }
  if (!payload || typeof payload !== 'object') {
    fail(CODES.WORKER_MALFORMED, 'worker output was not an object');
  }
  if (payload.is_error === true) {
    fail(CODES.WORKER_FAILED, `worker reported an error: ${redact(payload.result ?? payload.subtype ?? '').slice(0, 400)}`);
  }
  const summary = typeof payload.result === 'string' ? payload.result : '';
  if (summary.trim() === '') {
    fail(CODES.WORKER_MALFORMED, 'worker returned no summary text');
  }
  return {
    summary: redact(summary),
    sessionId: typeof payload.session_id === 'string' ? payload.session_id : null,
    numTurns: typeof payload.num_turns === 'number' ? payload.num_turns : null,
    costUsd: typeof payload.total_cost_usd === 'number' ? payload.total_cost_usd : null,
  };
}

/**
 * Run one worker turn in `cwd` (always a task worktree).
 *
 * @returns {Promise<{summary:string, sessionId:string|null, exitCode:number, durationMs:number, stderr:string}>}
 */
export async function runWorker({
  prompt,
  cwd,
  bin = 'claude',
  model = DEFAULT_WORKER_MODEL,
  sessionId = randomUUID(),
  resumeSessionId = null,
  maxBudgetUsd = null,
  timeoutMs = 60 * 60_000,
  spawnImpl = spawn,
} = {}) {
  const args = buildArgs({ model, sessionId, resumeSessionId, maxBudgetUsd, addDir: cwd });
  const startedAt = Date.now();

  const outcome = await new Promise((resolve) => {
    const child = spawnImpl(bin, args, {
      cwd,
      shell: false,
      env: process.env,
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';
    let timedOut = false;

    child.stdout?.on('data', (d) => {
      stdout += d;
    });
    child.stderr?.on('data', (d) => {
      stderr += d;
    });

    const timer = setTimeout(() => {
      timedOut = true;
      child.kill('SIGKILL');
    }, timeoutMs);

    child.on('error', (error) => {
      clearTimeout(timer);
      resolve({ started: false, error, stdout, stderr, exitCode: null, timedOut });
    });
    child.on('close', (exitCode) => {
      clearTimeout(timer);
      resolve({ started: true, error: null, stdout, stderr, exitCode, timedOut });
    });

    // The prompt is data, and stdin is where data belongs.
    child.stdin?.end(prompt);
  });

  const durationMs = Date.now() - startedAt;

  if (!outcome.started) {
    fail(CODES.CLAUDE_MISSING, `could not start "${bin}": ${redact(outcome.error?.message ?? '')}`);
  }
  if (outcome.timedOut) {
    fail(CODES.WORKER_FAILED, `worker exceeded ${Math.round(timeoutMs / 60_000)} minutes and was killed`, {
      sessionId,
    });
  }
  if (outcome.exitCode !== 0) {
    fail(
      CODES.WORKER_FAILED,
      `worker exited ${outcome.exitCode}: ${redact(outcome.stderr || outcome.stdout).slice(0, 400)}`,
      { sessionId },
    );
  }

  const parsed = parseResult(outcome.stdout);
  return {
    ...parsed,
    // Prefer the id we chose: it is the one that exists even when parsing fails.
    sessionId: parsed.sessionId ?? sessionId,
    exitCode: outcome.exitCode,
    durationMs,
    stderr: redact(outcome.stderr).slice(-2000),
  };
}
